site_name: Zevendaal Roleplay regels
site_url: 'https://github.com/DopeSmokahh/Regels-Zevendaal-Roleplay.git'
site_description: 'Wet en regelgeving van Zevendaal roleplay'
site_author: 'Zevendaal'

# Repository
## repo_url: 'https://github.com/DopeSmokahh/Regels-Zevendaal-Roleplay.git'
##repo_name: 'Zevendaal Regels'


theme:
  name: material
  features:
      - navigation.instant
      - navigation.tracking
      - navigation.indexes
      - header.autohide
      - toc.follow
      - content.action.edit
      - content.action.view

      - navigation.top
      - content.tabs.links
      - content.code.annotation
      - content.code.copy
      - navigation.sections
      - search.suggest
      - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:  
        icon: material/weather-sunny
        name: Switch to system preference        
          

copyright: Copyright &copy; 2024 Zevendaal Roleplay
markdown_extensions:
  - admonition
  - attr_list
nav:
    - Home: APV.md
    - APV Zevendaal: APV.md
    - Discord regels: Discord Regels.md
    - Offroadvoertuigen: Offroadvoertuigen.md
    - Streamen op zevendaal: Streamen.md
    - Kosten:
        - Ambulance: kosten/ambulance.md
        - ANWB: kosten/ANWB.md
        - Politie: kosten/politie.md


## new 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
